### ISSUE TITLE
Attestierung: mehrere Files gleichzeitig anzeigen

### ISSUE THREAD

**Issue by mhecker** [KITPraktomatTeam/Praktomat#101]

**Comment by ifrh** [comment]
As Feature-Request I would like to let it be open. Our Praktomat-Instance let a Tutor download via "Attestation > Preview" the solution files from a student as zip-file. But it would be nice, if the original solution files are shown in the case when "Annotated Files" would not be shown.

**Comment by ifrh** [comment]
@mhecker : I am unsure if your wanted feature has been included into Praktomat. But "my" feature request has been merged with pullrequest https://github.com/KITPraktomatTeam/Praktomat/pull/267 in October 2019. So perhaps this feature request can be closed too?

**Comment by ifrh** [comment]
I vote for closing this issue.
