### ISSUE TITLE
Login with is_active == False fails without message

### ISSUE THREAD

**Issue by nomeata** [KITPraktomatTeam/Praktomat#169]
When a user with flag "active = false" tries to log in using Shibboleth, he is immediately logged out again (by virtue of LogoutInactiveUserMiddleware). This is not very user friendly. Should the user be redirected to an error message?

**Comment by ratefuchs** [comment]
Now, with Shibboleth, the user is sent to a special page, and the trainer can set a dedicated error message. Without Shibboleth, an error message "This account is inactive." appears.
