### ISSUE TITLE
JUnit checker seems to be crashing

### ISSUE THREAD

**Issue by jkrinke** [KITPraktomatTeam/Praktomat#214]
I tried to use a JUnit checker with the current version however, I was not able to get it working.

Whenever I tried it, Praktomat crashed due to object_id being None.  I tried to debug it and it seems that the use of the Java Builder inside the JUnit checker is causing some problems as its CheckerResult object is not properly initialised.

I have disabled the JUnit checker for now.

**Comment by juliushaertl** [comment]
I ran into the same problem. Are there any news about this issue?

**Comment by juliushaertl** [comment]
My solution for now is to comment out the compilation part inside the JUnitChecker and compile all JUnit Test classes manually.
