### ISSUE TITLE
clean_user no longer exists in django

### ISSUE THREAD

**Issue by jkrinke** [KITPraktomatTeam/Praktomat#221]
When used with a newer django, the user registration fails due to the missing method 'clean_user' which has been removed from django.

As I don't know the best way to deal with it, I have not created a pull request. However, the fix I did was in  src/accounts/forms.py:

```
--- a/src/accounts/forms.py
+++ b/src/accounts/forms.py
@@ -58,13 +58,8 @@ class MyRegistrationForm(UserBaseCreationForm):
                return data
 
        def clean_username(self):
-               username = super(MyRegistrationForm,self).clean_username()
-               try:
-                       User.objects.get(username__iexact=username)
-               except User.DoesNotExist:
-                       return username
-               raise forms.ValidationError(_("A user with that username already exists."))
-
+               username = self.cleaned_data["username"]
+               return username
 
        @transaction.atomic
        def save(self):
@@ -124,12 +119,8 @@ class AdminUserCreationForm(UserBaseCreationForm):
                 fields = "__all__"
 
        def clean_username(self):
-               username = super(AdminUserCreationForm,self).clean_username()
-               try:
-                       User.objects.get(username__iexact=username)
-               except User.DoesNotExist:
-                       return username
-               raise forms.ValidationError(_("A user with that username already exists."))
+               username = self.cleaned_data["username"]
+               return username
 
 class AdminUserChangeForm(UserBaseChangeForm):
        class Meta:
```

**Comment by nomeata** [comment]
Just for the record: What version precisely of of Django is that?

**Comment by jkrinke** [comment]
It is the one automatically installed through "pip install -r Praktomat/requirements.txt”.

Django version 1.8.5

Thanks, 
Jens

> On 11 Jan 2016, at 13:57, Joachim Breitner <notifications@github.com> wrote:
> 
> Just for the record: What version precisely of of Django is that?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 
Jens Krinke, Senior Lecturer, UCL Computer Science
Deputy Director, CREST

**Comment by andromeda979** [comment]
Hi, I have the same problem!
I tested well with Django 1.9.4
but it does not go!
tnx


Environment:
Request Method: POST
Request URL: http://localhost:8000/admin/accounts/user/add/

Django Version: 1.9.4
Python Version: 2.7.6
Installed Applications:
('debug_toolbar',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'django.contrib.staticfiles',
 'django_extensions',
 'tinymce',
 'configuration',
 'accounts',
 'tasks',
 'solutions',
 'attestation',
 'checker',
 'utilities')
Installed Middleware:
('debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'accounts.middleware.AuthenticationMiddleware',
 'accounts.middleware.LogoutInactiveUserMiddleware')



Traceback:

File "/var/www/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/var/www/env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/www/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py" in wrapper
  541.                 return self.admin_site.admin_view(view)(*args, **kwargs)

File "/var/www/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/var/www/env/local/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "/var/www/env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py" in inner
  244.             return view(request, *args, **kwargs)

File "/var/www/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapper
  67.             return bound_func(*args, **kwargs)

File "/var/www/env/local/lib/python2.7/site-packages/django/views/decorators/debug.py" in sensitive_post_parameters_wrapper
  76.             return view(request, *args, **kwargs)

File "/var/www/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in bound_func
  63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/var/www/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapper
  67.             return bound_func(*args, **kwargs)

File "/var/www/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/var/www/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in bound_func
  63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/var/www/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  184.                     return func(*args, **kwargs)

File "/var/www/env/local/lib/python2.7/site-packages/django/contrib/auth/admin.py" in add_view
  128.                                                extra_context)

File "/var/www/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py" in add_view
  1437.         return self.changeform_view(request, None, form_url, extra_context)

File "/var/www/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapper
  67.             return bound_func(*args, **kwargs)

File "/var/www/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/var/www/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in bound_func
  63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/var/www/env/local/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  184.                     return func(*args, **kwargs)

File "/var/www/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py" in changeform_view
  1370.             if form.is_valid():

File "/var/www/env/local/lib/python2.7/site-packages/django/forms/forms.py" in is_valid
  161.         return self.is_bound and not self.errors

File "/var/www/env/local/lib/python2.7/site-packages/django/forms/forms.py" in errors
  153.             self.full_clean()

File "/var/www/env/local/lib/python2.7/site-packages/django/forms/forms.py" in full_clean
  362.         self._clean_fields()

File "/var/www/env/local/lib/python2.7/site-packages/django/forms/forms.py" in _clean_fields
  383.                     value = getattr(self, 'clean_%s' % name)()

File "/var/www/Praktomat/src/accounts/forms.py" in clean_username
  127. 		username = super(AdminUserCreationForm,self).clean_username()

Exception Type: AttributeError at /admin/accounts/user/add/
Exception Value: 'super' object has no attribute 'clean_username'

**Comment by andromeda979** [comment]
Hello, sorry for the inconvenience,
you have found the solution?
I have the same problem I too


    class AdminUserCreationForm(UserBaseCreationForm):

    	class Meta:

    		model = User

                    fields = "__all__"

    	def clean_username(self):

                		username = super(AdminUserCreationForm,self).clean_username()

     ...

    		try:

    			User.objects.get(username__iexact=username)

    		except User.DoesNotExist:

    			return username

    		raise forms.ValidationError(_("A user with that username already exists."))

▼ Local vars
Variable 	Value
self 	

<UserForm bound=True, valid=True, fields=(username;password1;password2)>

**Comment by jkrinke** [comment]
andromeda979, try to apply the patch I have given above. Let us know if it works.

Jens

**Comment by andromeda979** [comment]
> jkrinke commented 8 minutes ago
> andromeda979, try to apply the patch I have given above. Let us know if it works.
> 
> Jens

Thanks for the answer, but where do I find the path!
Thanks again!!

**Comment by jkrinke** [comment]
src/accounts/forms.py

**Comment by andromeda979** [comment]
nothing! it does not work!

```
'super' object has no attribute 'clean_username'


/var/www/Praktomat/src/accounts/forms.py in clean_username

    class AdminUserCreationForm(UserBaseCreationForm):

    	class Meta:

    		model = User

                    fields = "__all__"

    	def clean_username(self):

                		username = super(AdminUserCreationForm,self).clean_username()

     ...

    		try:

    			User.objects.get(username__iexact=username)

    		except User.DoesNotExist:

    			return username

    		raise forms.ValidationError(_("A user with that username already exists."))
```

**Comment by andromeda979** [comment]
> AttributeError at /admin/accounts/user/add/
> 
> 'super' object has no attribute 'clean_username'
> 
> Request Method: 	POST
> Request URL: 	http://localhost/admin/accounts/user/add/
> Django Version: 	1.8.5
> Exception Type: 	AttributeError
> Exception Value: 	
> 
> 'super' object has no attribute 'clean_username'
> 
> Exception Location: 	/var/www/Praktomat/src/accounts/forms.py in clean_username, line 127
> Python Executable: 	/usr/bin/python
> Python Version: 	2.7.6
> Python Path: 	
> 
> ['/usr/lib/python2.7',
>  '/usr/lib/python2.7/plat-x86_64-linux-gnu',
>  '/usr/lib/python2.7/lib-tk',
>  '/usr/lib/python2.7/lib-old',
>  '/usr/lib/python2.7/lib-dynload',
>  '/usr/local/lib/python2.7/dist-packages',
>  '/usr/lib/python2.7/dist-packages',
>  '/usr/lib/python2.7/dist-packages/PILcompat',
>  '/usr/lib/python2.7/dist-packages/gtk-2.0',
>  '/usr/lib/python2.7/dist-packages/ubuntu-sso-client',
>  '/var/www/env/lib/python2.7/site-packages',
>  '/var/www/Praktomat/src']
> 
> Server time: 	Mo, 14 Mär 2016 11:05:35 +0100

**Comment by jkrinke** [comment]
The log shows no presence of the patch. Have you applied it? And have you done the steps to upgrade your installation? Otherwise it will still run the old version.

**Comment by andromeda979** [comment]
I did a fresh install

> The log shows no presence of the patch. Have you applied it? And have you done the steps to upgrade your installation? Otherwise it will still run the old version.

**Comment by jkrinke** [comment]
But there is no presence of the patch. Have you applied it?

**Comment by andromeda979** [comment]
Excuse me, maybe I did not understand,
src / accounts / forms.py is this = https://github.com/KITPraktomatTeam/Praktomat/blob/master/src/accounts/forms.py

> But there is no presence of the patch. Have you applied it?

**Comment by jkrinke** [comment]
No, the patch I have given at the top of the issue. It has not been integrated into the distribution and you have to apply it yourself: https://github.com/KITPraktomatTeam/Praktomat/issues/221

**Comment by andromeda979** [comment]
thanks for everything, I'm sorry but I did not realize!
thanks again for your help
I did so:

my src/account/form.py
```
> def clean_username(self):
>                 username = super(AdminUserCreationForm,self).clean_username()
>                 try:
>                         User.objects.get(username__iexact=username)
>                 except User.DoesNotExist:
>                         return username
>                 raise forms.ValidationError(_("A user with that username already exists."))
>                 username = self.cleaned_data["username"]
>                 return username
> 
> 
>         @transaction.atomic
>         def save(self):
>                 user = super(MyRegistrationForm, self).save()
> 
>                 # default group: user
>                 user.groups = Group.objects.filter(name='User')
> 
>                 # disable user until activated via email
>                 user.is_active=False
> 
>                 user.set_new_activation_key()
> 
>                 user.mat_number=self.cleaned_data.get("mat_number")
> 
>                 user.save()
> 
```


my log:

```
/var/www/Praktomat/src/accounts/forms.py in clean_username

    class AdminUserCreationForm(UserBaseCreationForm):

    	class Meta:

    		model = User

                    fields = "__all__"

    	def clean_username(self):

                		username = super(AdminUserCreationForm,self).clean_username()

     ...

    		try:

    			User.objects.get(username__iexact=username)

    		except User.DoesNotExist:

    			return username

    		raise forms.ValidationError(_("A user with that username already exists."))



```

**Comment by andromeda979** [comment]
thanks for everything, I'm sorry but I did not realize!
thanks again for your help
I did so:

my src/account/form.py

```
class MyRegistrationForm(UserBaseCreationForm):
.......
     def clean_username(self):
                username = super(MyRegistrationForm,self).clean_username()
                try:
                        User.objects.get(username__iexact=username)
                except User.DoesNotExist:
                        return username
                raise forms.ValidationError(_("A user with that username already exists."))
                username = self.cleaned_data["username"]
                return username

class AdminUserCreationForm(UserBaseCreationForm):
..............

 def clean_username(self):
                username = super(AdminUserCreationForm,self).clean_username()
                try:
                        User.objects.get(username__iexact=username)
                except User.DoesNotExist:
                        return username
                raise forms.ValidationError(_("A user with that username already exists."))
                username = self.cleaned_data["username"]
                return username


```

my log: 

```
> 'super' object has no attribute 'clean_username'
> 
> Request Method: 	POST
> Request URL: 	http://localhost/admin/accounts/user/add/
> Django Version: 	1.8.5
> Exception Type: 	AttributeError
> Exception Value: 	
> 
> 'super' object has no attribute 'clean_username'
> 
> Exception Location: 	/var/www/Praktomat/src/accounts/forms.py in clean_username, line 129
> Python Executable: 	/usr/bin/python
> Python Version: 	2.7.6
> Python Path: 	
> 
> ['/usr/lib/python2.7',
>  '/usr/lib/python2.7/plat-x86_64-linux-gnu',
>  '/usr/lib/python2.7/lib-tk',
>  '/usr/lib/python2.7/lib-old',
>  '/usr/lib/python2.7/lib-dynload',
>  '/usr/local/lib/python2.7/dist-packages',
>  '/usr/lib/python2.7/dist-packages',
>  '/usr/lib/python2.7/dist-packages/PILcompat',
>  '/usr/lib/python2.7/dist-packages/gtk-2.0',
>  '/usr/lib/python2.7/dist-packages/ubuntu-sso-client',
>  '/var/www/env/lib/python2.7/site-packages',
>  '/var/www/Praktomat/src']
> 
> Server time: 	Mo, 14 Mär 2016 12:21:55 +0100
```

```
/var/www/Praktomat/src/accounts/forms.py in clean_username

    class AdminUserCreationForm(UserBaseCreationForm):

    	class Meta:

    		model = User

                    fields = "__all__"

    	def clean_username(self):

                		username = super(AdminUserCreationForm,self).clean_username()

     ...

    		try:

    			User.objects.get(username__iexact=username)

    		except User.DoesNotExist:

    			return username

    		raise forms.ValidationError(_("A user with that username already exists."))

                    username = self.cleaned_data["username"]

▼ Local vars
Variable 	Value
self 	

<UserForm bound=True, valid=True, fields=(username;password1;password2)>
```

**Comment by jkrinke** [comment]
Do you know how to apply a patch?  Your code does not contain the patch I have given.  Your code should look like:

        def clean_username(self):
              username = self.cleaned_data["username"]
              return username

**Comment by lohner** [comment]
As far as I understand the issue, with Django 1.8 there is no need for `UserCreationForm.clean_username` anymore if there is no actual "cleaning" of the supplied username.

Up to Django 1.7 a `ValidationError` was thrown in `clean_username` if the given name was already taken (see [here](https://github.com/django/django/blob/1.7.11/django/contrib/auth/forms.py#L96)), albeit a `ValidationError` would have been thrown by the uniqueness check in the core database model later (see [here](https://github.com/django/django/blob/1.7.11/django/db/models/base.py#L791)). However it is done in `clean_username` to set a proper error message.

Since Django 1.8, the error message is set by the `error_messages` property (see [here](https://github.com/django/django/blob/1.8/django/contrib/auth/models.py#L395)). Which gets propagated to the `ValidationError` thrown in the core database model (have a [look](https://github.com/django/django/blob/1.8/django/db/models/base.py#L1098)).

So in my opinion the fix for this issue would be to simply remove both `clean_username` functions completely.

**Comment by nomeata** [comment]
Thanks for the investigation, sounds resonable.
