### ISSUE TITLE
Resubmit Solution => Java Compiler failed <= includes patch for src/solution/models.py

### ISSUE THREAD

**Issue by ifrh** [KITPraktomatTeam/Praktomat#232]
Resubmit Solution => Java Compiler failed <= 
If new SolutionNumber has more position than the old SolutionNumber
the filename while copying into Sandbox got damaged: i.e:
SolutionArchive/[...]/Solution_9993/AlgoSchlange.java
SolutionSandbox/[...]/Solution_10039/lgoSchlange.java
# ========8<=================

`patch file for src/solution/models.py`
[solutions-mode-patch.txt](https://github.com/KITPraktomatTeam/Praktomat/files/251890/solutions-mode-patch.txt)

**Comment by nomeata** [comment]
Thanks for the report. I’m not sure about the fix (regexes seem to be rather fragile). I guess I will have to sit down and think this through and come up with a proper fix (unless @mhecker beats me to it).

**Comment by ifrh** [comment]
Because @ratefuchs had merged the bugfix from pull request https://github.com/KITPraktomatTeam/Praktomat/pull/266 via commit https://github.com/KITPraktomatTeam/Praktomat/commit/b24d1c33a6e3b480217d13aaded969b06e278010 into master I close this issue.
