### ISSUE TITLE
Checker list

### ISSUE THREAD

**Issue by andromeda979** [KITPraktomatTeam/Praktomat#235]
Dear all,
I need your help, I have to organize the Task Checker list.
I would only 3 items in the list, namely:

- Text Checker

- Script Checker

- CBuilder

How can I do?

Thank you very much

![list](https://cloud.githubusercontent.com/assets/17449718/16866966/47a759b6-4a6f-11e6-8401-c9f705ddbd81.PNG)

**Comment by nomeata** [comment]
What you see is the list of available checkers. By clicking on them, you add them to the task. So simply first add the Text checker, then the Script checker, and then the CBuilder.

You can later reorder them by drag’n’drop.
