### ISSUE TITLE
Compiler C

### ISSUE THREAD

**Issue by andromeda979** [KITPraktomatTeam/Praktomat#240]
Hello, 
I would like to note a modification that could be useful. 
When we select the compiler we already know that it is a necessary requirement. A program with an error does not compile.

That is why I have made this small modification so ‘Required’ is automatically selected in the Compiler C.

CBuilder.py

```
+ from checker.compiler.Builder import Builder

class CheckerForm(AlwaysChangedModelForm):
    """ override default values for the model fields """
    def __init__(self, **args):
        super(CheckerForm, self).__init__(**args)
             + self.fields["required"].initial = True

```

I do hope this is some help!

**Comment by ifrh** [comment]
I created a pullrequest for our C/C++/UnitCheckers, see https://github.com/KITPraktomatTeam/Praktomat/pull/298
