### ISSUE TITLE
Scala and SBT compiler

### ISSUE THREAD

**Issue by andromeda979** [KITPraktomatTeam/Praktomat#243]
Hello everybody,
I wanted to implement **Scala** in Praktomat with **SBT compiler,** I’m wondering if anyone had already done something!
Thank you in advance

**Comment by mhecker** [comment]
Based on your commits, the e2c766d09b826d4f1f81bb690d773fae6d01e017 introduced some rudimentary support for Scala.  Please reopen if you encounter problems, or some critical feature is  missing!
