### ISSUE TITLE
apache2-mpm-worker

### ISSUE THREAD

**Issue by physikerwelt** [KITPraktomatTeam/Praktomat#244]
https://github.com/KITPraktomatTeam/Praktomat#prerequisites lists `apache2-mpm-worker` as a prerequisite, which does not exist in ububtu 16LTS.

**Comment by nomeata** [comment]
I guess the package got merged into the main apache package. One someone (you?) tested Praktomat on 16LTS, this section can be adjusted. Pull requests are welcome!

**Comment by physikerwelt** [comment]
Yes, I installed Praktomat on Ubuntu 16LTS and I could see the UI (I would not say, I tested it).
I executed the following commands
```
sudo apt install postgresql apache2-mpm-worker libpq-dev zlib1g-dev libmysqlclient-dev libsasl2-dev libssl-dev swig libapache2-mod-xsendfile libapache2-mod-wsgi junit junit4 dejagnu gcj-jdk virtualenv python-pip
git clone --recursive git://github.com/KITPraktomatTeam/Praktomat.git
cd Praktomat
virtualenv --system-site-packages env/
. env/bin/activate
pip install -r requirements.txt
```

**Comment by mhecker** [comment]
That package got merged, indeed. See e.g. http://askubuntu.com/questions/808556/apache2-mpm-worker-missing-in-ubuntu-16-04. So on 16.04LTS the `apache2-mpm-worker` should indeed be unnecessary.

When you say that you could "see the UI", did you successfully setup Praktomat to be served through Apache, or did you use the developer setup (by running `./src/manage-devel.py runserver`)?

**Comment by physikerwelt** [comment]
I did use the developer setup which looked like that:
![2016-11-22 1](https://cloud.githubusercontent.com/assets/2777736/20535966/6cc6219e-b0e7-11e6-8bf6-48309d8b7daa.png)

**Comment by physikerwelt** [comment]
My point is the following: If people are following the readme on ubuntu 16 they'll see a error in the second step. I suggest to add a note to the readme.
