### ISSUE TITLE
junit checker requires a main routine

### ISSUE THREAD

**Issue by physikerwelt** [KITPraktomatTeam/Praktomat#247]
Is there a specific reason why the junit checker requires a main routine.
After adding an empty main function to my junit test class the tests ran fine, which was not the case before. In the java builder there is a "main required" checkbox which is not availile be in the junit checker section. (See screenshot)
![2016-11-24 1](https://cloud.githubusercontent.com/assets/2777736/20606567/171eb4ea-b272-11e6-99b8-cf890c2b3523.png)

**Comment by mhecker** [comment]
Please re-open if this fix does not do what you expect.

**Comment by physikerwelt** [comment]
I can confirm that this was fixed.
