### ISSUE TITLE
Configuration of deployment installation

### ISSUE THREAD

**Issue by physikerwelt** [KITPraktomatTeam/Praktomat#250]
I only discovered a few minor issues (#244, #246, #247, #248)  while testing the developer setup.
However, I got completely stuck with deployment setup.
```Configure Praktomat in Praktomat/src/settings/local.py, to set data base names and paths.```
turns out to be much harder than it seems.
After two days of trail and error I'm still not able to log into the web UI due to a
```
    CSRF cookie not set.
```
exception even though there is a cookie called `csrftoken`.
Is there somewhere a more detailed guide on setting up a `deployment` environment.

**Comment by nomeata** [comment]
No, there is unfortunately no better guide. Is the cookie maybe old and not actually update in the browser? Was a secret key file properly generated by the code in `defaults` (I guess a cookie generated with the wrong secret key might be ignored)?

**Comment by physikerwelt** [comment]
@nomeata How can I check the secret key file?

What would really help for the configuration is the directory structure on the kit server and the corresponding web services. Especially this section
https://github.com/KITPraktomatTeam/Praktomat/blob/master/src/settings/local.py#L15-L53
suggests that there is a certain best practice naming convention that should be applied.

**Comment by nomeata** [comment]
That part is pretty KIT-specific. If you just have one instance, just scrap the whole code and set `SITE_NAME` directly. Similarly with other conditional statements further down.

**Comment by nomeata** [comment]
> @nomeata How can I check the secret key file?

Praktomat should automatically create a file `SECRET_KEY` in the `UPLOAD_ROOT` directory. If that is not the case, maybe some permissions are wrong?

**Comment by ifrh** [comment]
Hi, here I hat to fix a bug inside class D for getting an automated `SECRET_KEY` see pull request #238 and there commit https://github.com/KITPraktomatTeam/Praktomat/pull/238/commits/35ab8e940d2c40df5d95f268aabfc25761d4cfdd

**Comment by mhecker** [comment]
I picked that particular commit now into our master: 6d8fdd23ea32579bcb4ff2b82c2e6faad1cf70b6 Thanks @ifrh.

 @physikerwelt does this work for you now!?!?

**Comment by physikerwelt** [comment]
@mhecker I started with the [test](https://github.com/KITPraktomatTeam/Praktomat/blob/master/src/settings/test.py) config. There the default values
```
SECRET_KEY = "not-so-secret"
# Private key used to sign uploded solution files in submission confirmation email
PRIVATE_KEY = join(dirname(dirname(dirname(__file__))), 'examples', 'certificates', 'privkey.pem')
```
work ok.
I think I'll have to look for a slightly bigger machine to test `USESAFEDOCKER` and the mail features which we currently do not use at all.

**Comment by ifrh** [comment]
Just now I saw, that there was a small typo in class D left.
Fixed in my pull request https://github.com/KITPraktomatTeam/Praktomat/pull/268

**Comment by ifrh** [comment]
> I only discovered a few minor issues (#244, #246, #247, #248) while testing the developer setup. However, I got completely stuck with deployment setup. `Configure Praktomat in Praktomat/src/settings/local.py, to set data base names and paths.` turns out to be much harder than it seems. 
> [...]
>  Is there somewhere a more detailed guide on setting up a `deployment` environment.

Are information in README (update on 19. February 2022) now better?

**Comment by ifrh** [comment]
@physikerwelt : perhaps this issue could be closed? How do you think about closing it?

**Comment by physikerwelt** [comment]
Sure close it...too old

**Comment by ifrh** [comment]
@ratefuchs , @KITPraktomatTeam : this issue should be closed. (Sadly I cannot do it.)
