### ISSUE TITLE
JUnit checker requires ignored files

### ISSUE THREAD

**Issue by physikerwelt** [KITPraktomatTeam/Praktomat#251]
Junit checker requires a
>space-seperated list of files to be ignored during compilation

However, it is not clear which files should go there.

Insering a space to the box resolves the problem

**Comment by mhecker** [comment]
I don't quite catch your meaning here. 

> However, it is not clear which files should go there.

So your issue is with the lack of documentation, fair enought, but..

> Insering a space to the box resolves the problem

so there seems to be an additional problem?

**Comment by physikerwelt** [comment]
@mhecker sorry for the lack clarity. I'll make an attempt to explain the situation better:

1. I don't understand the concept of ignored files.
2. If I enter a space into that box, praktomat works as expected.

I reported 2 in addition, because I assume that this is not the expected behaviour. In particular I don't understand why it works with a single whitespace but not with an empty string. Is the issue description clear now?

**Comment by mhecker** [comment]
no problem, i'd just like to know what bad things happen for you if you provide an empty string, only :)
