### ISSUE TITLE
figure out memory requirement for safe-docker usage

### ISSUE THREAD

**Issue by physikerwelt** [KITPraktomatTeam/Praktomat#252]
After setting up safe-docker and adjusting the permissions, the java compiler outputs a warning which seems to be interpreted as failure.
```Java compiler output:

WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.
```
According to google this might be connect to the format that is used to specify the memory limit. However, it does not work for either setting
```
TEST_MAXMEM = 134217728
```
or
```
TEST_MAXMEM = 128m
```
or not configured.

**Comment by mhecker** [comment]
This is strange, and i cannot currently reproduce.

Note that neither of your two tries are what you want,  since `TEST_MAXMEM` is appended to the safe-docker call like this:

```python
                if maxmem is not None:
                    command += ["--memory", "%sm" % maxmem]
```
, see `src/utilities/safeexec.py`

**Comment by ifrh** [comment]
@physikerwelt : How have you solved your problem or has the problem disappeared by time goes by?

**Comment by physikerwelt** [comment]
Yes, it is resolved. We found a solution without docker.
