### ISSUE TITLE
Allow the use of tmp files

### ISSUE THREAD

**Issue by physikerwelt** [KITPraktomatTeam/Praktomat#254]
This more a question than a bug.
I was wondering which is the best way to allow the creation of temp files in junit test.
The test was using 
```java
java.io.File.createTempFile
```
To let the test pass I added the following config line to
https://github.com/KITPraktomatTeam/Praktomat/blob/be2e62ec4dd3530ebf3adc01c29a53703683af6a/src/checker/scripts/eclipse-junit.policy#L5
```
	permission java.io.FilePermission "/tmp/-", "read,write,delete";
```
Is that a good idea?

**Comment by mhecker** [comment]
seems OK to me, especially when you're using docker (and hence nothing in `/tmp` is shared).

Ourselves, we sometime used permissions like

```
permission java.io.FilePermission "tests/*","read";
```

which at least were  intended to grant acces only some directory relative to the testing directory. What we needed to prevent here was that  as submission could read the (secret) JunitTests.java files that are placed in the testing directory.
