### ISSUE TITLE
UserWarning while running "pip install -Ur Praktomat/requirements.txt"  // DEPRECATION: pip will drop support for Python 2.7

### ISSUE THREAD

**Issue by ifrh** [KITPraktomatTeam/Praktomat#294]
`python --version`  => `Python 2.7.6`
`pip --version` => `pip 18.1`

running `pip install -Ur Praktomat/requirements.txt`, as mentioned in https://github.com/KITPraktomatTeam/Praktomat/issues/292#issuecomment-437828860 for updating my virtual environment, I got :

> site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
>   utils.DeprecatedIn23,
> 
> 

> site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.

**Comment by ifrh** [comment]
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.

**Comment by ratefuchs** [comment]
Fixed since we now use Python 3.
