### ISSUE TITLE
require consent to disclaimer leads to endless redirect loop

### ISSUE THREAD

**Issue by chris21k** [KITPraktomatTeam/Praktomat#310]
After applying yesterday's feature update "require users to consent to disclaimer before using…" and enabling "Requires disclaimer acceptance" in the adimin panel's settings, the navigation of each site leads to an redirection error. (Firefox in German: "Fehler: Umleitungsfehler\n Beim Verbinden mit $host trat ein Fehler auf."). The same under Chrome.

**Comment by ratefuchs** [comment]
Does the new commit 7bb37ef fix it for you?

**Comment by chris21k** [comment]
That seems to fix it. Thanks for the fast response!
