### ISSUE TITLE
Crash: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 246: ordinal not in range(128)

### ISSUE THREAD

**Issue by DeveloperTK** [KITPraktomatTeam/Praktomat#313]
Hi, I recently came across this crash in my solution:

    Crash: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 246: ordinal not in range(128)

    File "pythomat.zip/pythomat/ipo.py", line 165, in run_multiple_tests
      run_single_test(checker, description)

    File "pythomat.zip/pythomat/ipo.py", line 129, in run_single_test
      classpath=classpath

    File "pythomat.zip/pythomat/submission.py", line 62, in execute_submission
      return stdout.decode().splitlines(), stderr.decode().splitlines(), returncode, timer.time

Unfortunately, I cannot provide any more information on this error. This happened at the KIT Praktomat instance in Task 4.B (14) of "2020_WS". (2020_WS/solutions/33185)

**Comment by ratefuchs** [comment]
This does not seem like a bug of the Praktomat project, seems more like a bug in the testing code provided by the organizers of this course.

**Comment by ifrh** [comment]
Just for the record 
Quote from: ( https://code.djangoproject.com/ticket/6009#comment:18 )

> Debian runs Apache with the LANG=C locale by default, which breaks uploading files with special characters in their names at least when running with mod_wsgi. Activating a UTF-8 locale in /etc/apache2/envvars should resolve the issue.
