### ISSUE TITLE
multiple but different defined d.AUTHENTICATION_BACKENDS in settings/defaults.py 

### ISSUE THREAD

**Issue by ifrh** [KITPraktomatTeam/Praktomat#324]
In Praktomat/src/settings/defauls.py there a two places where d.AUTHENTICATION_BACKENDS is defined in different ways:

https://github.com/KITPraktomatTeam/Praktomat/blob/aafbeb16c8200c48c0e89074bf22b162ab329d96/src/settings/defaults.py#L126-L128

https://github.com/KITPraktomatTeam/Praktomat/blob/aafbeb16c8200c48c0e89074bf22b162ab329d96/src/settings/defaults.py#L374-L377

This could be a problem, if these settings are not overwritten via local.py, because

- > The order of [AUTHENTICATION_BACKENDS](https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-AUTHENTICATION_BACKENDS) matters, so if the same username and password is valid in multiple backends, Django will stop processing at the first positive match.

- > You can use [AllowAllUsersModelBackend](https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.backends.AllowAllUsersModelBackend) or [AllowAllUsersRemoteUserBackend](https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.backends.AllowAllUsersRemoteUserBackend) if you want to allow inactive users to authenticate.
Changed in Django 1.10: In older versions, the [ModelBackend](https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.backends.ModelBackend) allowed inactive users to authenticate.

Above bulletpoints are taken from Django-Docs:

1.  https://docs.djangoproject.com/en/4.0/topics/auth/customizing/#authentication-backends 

2.  https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#authorization-for-inactive-users

**Comment by ifrh** [comment]
@hannesbraun @ratefuchs I think `accounts.ldap_auth.LDAPBackend` should be the first and `django.contrib.auth.backends.AllowAllUsersModelBackend` should be the second entry in `d.AUTHENTICATION_BACKENDS`.
And there is no need to mention  `django.contrib.auth.backends.ModelBackend` inside settings/defaults.py.

**Comment by hannesbraun** [comment]
I agree with that. The `ModelBackend` should be replaced with the `AllowAllUsersModelBackend`. For the sake of simplicity, it's probably also a good idea to merge those two parts into one where the `AUTHENTICATION_BACKENDS` are set.
