### ISSUE TITLE
Feature: Reenable travis builds....

### ISSUE THREAD

**Issue by ifrh** [KITPraktomatTeam/Praktomat#340]
Currently (25.5.2022) Travis builds for Praktomat seems to be deactivated:
Travis informs on [[1]](https://travis-ci.org/github/KITPraktomatTeam/Praktomat/branches) 

> Since June 15th, 2021, the building on [travis-ci.org](http://www.travis-ci.org/) is ceased. Please use [travis-ci.com](http://www.travis-ci.com/) from now on.

The latest builds on Travis-ci.org [[2]](https://travis-ci.org/github/KITPraktomatTeam/Praktomat/builds) failed about a year ago.

Sadly on Travis-ci.com [[3]](https://travis-ci.com/github/KITPraktomatTeam/Praktomat/branches) you get the following message:

> We couldn't display the repository KITPraktomatTeam/Praktomat 

I asked Travis support how public open source projects can build on travis-ci.com for free, after reading  the information they had given on webpages: 

- https://blog.travis-ci.com/2021-05-07-orgshutdown , 
- https://docs.travis-ci.com/user/billing-overview/ , 
- https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source

The answer was:

> 
> We offer an Open Source Subscription for free to non-commercial open-source projects. To qualify for an Open Source subscription, the project must meet the following requirements:
>  
> 
>     You are a project lead or regular committer (latest commit in the last month)
>     Project must be at least 3 months old and is in active development (with regular commits and activity)
>     Project meets the [OSD](https://opensource.org/docs/osd) specification
>     Project must not be an expressly commercial project
>     Project can not provide commercial services or distribute paid versions of the software
> 
>  
> Does this sound like you and your project? We'd be very happy to support you!

[1] https://travis-ci.org/github/KITPraktomatTeam/Praktomat/branches
[2] https://travis-ci.org/github/KITPraktomatTeam/Praktomat/builds
[3] https://travis-ci.com/github/KITPraktomatTeam/Praktomat/branches

**Comment by hannesbraun** [comment]
Another option would be to switch to GitHub Actions. As it's better integrated with GitHub, this might be more convenient to use and we don't have to rely on a third party. I've already ported the Travis build/test and as far as I can tell, everything seems to work as good as before. See #341 for the corresponding pull request. The only exception is that installing `gcj-jdk` is not possible anymore. However, as the tests don't depend on that package, this shouldn't be a problem.

If you'd like to stick with Travis, feel free to close my pull request. I don't want to force anybody to use GitHub Actions ;)
