### ISSUE TITLE
Remove GCJ support

### ISSUE THREAD

**Issue by hannesbraun** [KITPraktomatTeam/Praktomat#344]
Right now, there's a checker/compiler in the Praktomat source code making use of the "GNU Compiler for the Java Programming Language" (GCJ). See [`src/checker/compiler/JavaGCCBuilder.py`](https://github.com/KITPraktomatTeam/Praktomat/blob/d7707f6b4f5d9b5c1eab61d8ea80313bf0486ff4/src/checker/compiler/JavaGCCBuilder.py)

This makes Praktomat depend on the availability of this compiler. (I know, you could just ignore it as long as you're not going to use it.) Still, I think it's time to remove this checker. As stated on the [GCJ website](https://gcc.gnu.org/wiki/GCJ):

> As of GCC 7, the GCC Java frontend and associated libjava runtime library have been removed from GCC.

The GCC 7 release was around 2017. The development on GCJ even stopped already somewhere in 2009. Right now, it's not available anymore as a package in recent releases of Ubuntu or Debian. Therefore, I think we should now remove support for GCJ.

Any thoughts on this? Otherwise, I'll just leave this issue open for a bit and submit a pull request for removing GCJ support somewhere in the future.

**Comment by ifrh** [comment]
Perhaps changing GCJ to ECJ "eclipse JDT Batch Compiler" , see https://manpages.ubuntu.com/manpages/xenial/man1/ecj.1.html , should be the replacement, to enable a java compiler, which gives other (additional) informations compared to original javac messages.

**Comment by hannesbraun** [comment]
Indeed, the JDT compiler might be some sort of a replacement (although its use case is a bit different).

I'm just wondering: would you actually be using it? I certainly won't. And if nobody else plans to use it, we don't need to implement it. We could then rather spend our time implementing other useful features ;)
